name: Permission repro called

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - run: echo reached
